/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

extern "C" {

// Modelname: obsfun_test
// Variables: x
// Parameters: offset
// Outputs: obs

void obsfun_test_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = x + obs * n_vars;
        (void)x_obs;  // suppress unused warning

        y[obs * n_out + 0] = p[0] - x_obs[0];
    }
}

void obsfun_test_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 1;
    const int n_symbols = 2;

    // Zero-initialize
    std::fill(jac, jac + n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = x + obs * n_vars;
        (void)x_obs;  // suppress unused warning
        jac[obs + n_obs * (0 + n_out * 0)] = -1.0;        jac[obs + n_obs * (0 + n_out * 1)] = 1.0;
    }
}

} // extern "C"
