/** Code auto-generated by CppODE 1.0.0 **/

#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <algorithm>
#include <vector>
#include <cmath>
#include <cppode/cppode.hpp>

using namespace boost::numeric::odeint;
namespace ublas = boost::numeric::ublas;

namespace {
// ODE system
struct ode_system {
  ublas::vector<double> params;
  std::vector<const cppode::PchipForcing<double>*> F;

  ode_system(const ublas::vector<double>& p_,
             const std::vector<const cppode::PchipForcing<double>*>& F_)
    : params(p_), F(F_) {}

  void operator()(const ublas::vector<double>& x,
                  ublas::vector<double>& dxdt,
                  const double& t) {
    dxdt[0] = -params[1]*x[0];
  }
};

// Jacobian for stiff solver
struct jacobian {
  ublas::vector<double> params;
  std::vector<const cppode::PchipForcing<double>*> F;

  jacobian(const ublas::vector<double>& p_,
           const std::vector<const cppode::PchipForcing<double>*>& F_)
    : params(p_), F(F_) {}

  void operator()(const ublas::vector<double>& x,
                  ublas::matrix<double>& J,
                  const double& t,
                  ublas::vector<double>& dfdt) {
    J(0,0) = -params[1];
    dfdt[0] = 0.0;
  }
};

// Observer: stores trajectory values in vectors
struct observer {
  std::vector<double>& times;
  std::vector<double>& y;

  explicit observer(std::vector<double>& t, std::vector<double>& y_)
    : times(t), y(y_) {}

  void operator()(const ublas::vector<double>& x, const double& t) {
    times.push_back(t);
    for (size_t i = 0; i < x.size(); ++i) y.push_back(x[i]);
  }
};

}

extern "C" SEXP solve_test_Xs_bs(SEXP timesSEXP, SEXP paramsSEXP, SEXP sens1iniSEXP, SEXP sens2iniSEXP, SEXP fixedSEXP, SEXP abstolSEXP, SEXP reltolSEXP, SEXP maxprogressSEXP, SEXP maxstepsSEXP, SEXP hiniSEXP, SEXP root_tolSEXP, SEXP maxrootSEXP, SEXP forcingTimesSEXP, SEXP forcingValuesSEXP) {
try {

  StepChecker checker(INTEGER(maxprogressSEXP)[0], INTEGER(maxstepsSEXP)[0]);

  ublas::vector<double> x(1);
  ublas::vector<double> full_params(4);

  // initialize variables
  for (int i = 0; i < 1; ++i) {
    bool is_fixed = false;
    (void)is_fixed;  // suppress unused warning
    x[i] = REAL(paramsSEXP)[i];
    full_params[i] = x[i];
  }

  // initialize parameters
  for (int i = 0; i < 3; ++i) {
    int param_index = 1 + i;
    bool is_fixed = false;
    (void)is_fixed;  // suppress unused warning
    full_params[param_index] = REAL(paramsSEXP)[param_index];
  }


  // --- Initialize forcings (PCHIP interpolation) ---
  int n_forcings = Rf_length(forcingTimesSEXP);
  std::vector<cppode::PchipForcing<double>> forcing_storage(n_forcings);
  std::vector<const cppode::PchipForcing<double>*> F(n_forcings);

  for (int fi = 0; fi < n_forcings; ++fi) {
    SEXP times_i = VECTOR_ELT(forcingTimesSEXP, fi);
    SEXP values_i = VECTOR_ELT(forcingValuesSEXP, fi);
    int n_points = Rf_length(times_i);

    std::vector<double> ftimes(REAL(times_i), REAL(times_i) + n_points);
    std::vector<double> fvalues(REAL(values_i), REAL(values_i) + n_points);

    forcing_storage[fi].initialize(ftimes, fvalues);
    F[fi] = &forcing_storage[fi];
  }


  // --- Copy integration times ---
  std::vector<double> times_dbl(REAL(timesSEXP), REAL(timesSEXP) + Rf_length(timesSEXP));

  // ensure time zero is included
  if (std::find(times_dbl.begin(), times_dbl.end(), 0.0) == times_dbl.end()) {
    times_dbl.push_back(0.0);
  }

  // sort times ascending and remove duplicates
  std::sort(times_dbl.begin(), times_dbl.end());
  times_dbl.erase(std::unique(times_dbl.begin(), times_dbl.end()), times_dbl.end());

  // convert to AD vector
  std::vector<double> times;
  times.reserve(times_dbl.size());
  for (double tval : times_dbl) {
    times.emplace_back(tval);
  }

  // storage for results
  std::vector<double> result_times;
  std::vector<double> y;

  // --- Event containers ---
  std::vector<FixedEvent<ublas::vector<double>, double>> fixed_events;
  std::vector<RootEvent<ublas::vector<double>, double>> root_events;
  // Fixed event 0: x at t = te
  fixed_events.emplace_back(FixedEvent<ublas::vector<double>, double>{
    full_params[3],  // time
    0,    // state_index
    [full_params, &F](const ublas::vector<double>& x, const double& t) -> double {
      return full_params[2];
    },  // value_func
    EventMethod::Add,  // method
    [full_params, &F](const ublas::vector<double>& x, const double& t) -> ublas::vector<double> {
      ublas::vector<double> grad(1);
      grad[0] = 0.0;
      return grad;
    }  // dh_dx_func
  });


  // --- Solver setup ---
  double abstol = REAL(abstolSEXP)[0];
  double reltol = REAL(reltolSEXP)[0];
  double root_tol = REAL(root_tolSEXP)[0];
  double hini = REAL(hiniSEXP)[0];
  int maxroot = INTEGER(maxrootSEXP)[0];
  ode_system sys(full_params, F);
  jacobian jac(full_params, F);
  observer obs(result_times, y);
  auto controlledStepper = rosenbrock4_controller_pi<rosenbrock4<double>>(abstol, reltol);
  auto denseStepper = rosenbrock4_dense_output_pi<decltype(controlledStepper)>(controlledStepper);

  // --- Determine dt ---
  double dt;
  if (hini == 0.0) {
    dt = odeint_utils::estimate_initial_dt_local(sys, jac, x, times.front(), abstol, reltol);
  } else {
    dt = hini;
  }

  // --- Integration ---
  integrate_times_dense(denseStepper, std::make_pair(sys, jac), x, times.begin(), times.end(), dt, obs, fixed_events, root_events, checker, root_tol, maxroot);

  const int n_out = static_cast<int>(result_times.size());
  if (n_out <= 0) Rf_error("Integration produced no output");

  // --- Return list(time, variable) ---
  SEXP ans = PROTECT(Rf_allocVector(VECSXP, 2));
  SEXP names = PROTECT(Rf_allocVector(STRSXP, 2));
  SET_STRING_ELT(names, 0, Rf_mkChar("time"));
  SET_STRING_ELT(names, 1, Rf_mkChar("variable"));
  Rf_setAttrib(ans, R_NamesSymbol, names);

  SEXP time_vec = PROTECT(Rf_allocVector(REALSXP, n_out));
  SEXP variable_mat = PROTECT(Rf_allocMatrix(REALSXP, n_out, 1));
  double* time_out = REAL(time_vec);
  double* variable_out = REAL(variable_mat);
  auto IDX = [n_out](int r, int c){ return r + c * n_out; };

  for (int i = 0; i < n_out; ++i) {
    time_out[i] = result_times[i];
    for (int s = 0; s < 1; ++s) {
      variable_out[IDX(i, s)] = y[i * 1 + s];
    }
  }

  SET_VECTOR_ELT(ans, 0, time_vec);
  SET_VECTOR_ELT(ans, 1, variable_mat);
  UNPROTECT(4);
  return ans;
  } catch (const std::exception& e) {
    Rf_error("ODE solver failed: %s", e.what());
  } catch (...) {
    Rf_error("ODE solver failed: unknown C++ exception");
  }
}
