/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>
#include <vector>
#include <cppode/cppode_dual_math.hpp>
#include <cppode/cppode_dual_expr.hpp>

// Modelname: expl_parfn_C1
// Variables: none
// Parameters: a, b, s0
// Outputs: a, b, s0

namespace {
template <typename T>
inline void expl_parfn_C1_eval_one(const T* x_obs, const T* p, T* y_local) {
    using std::exp; using std::log; using std::sqrt; using std::pow;
    using std::sin; using std::cos; using std::tan;
    using std::asin; using std::acos; using std::atan; using std::atan2;
    using std::sinh; using std::cosh; using std::tanh;
    using std::asinh; using std::acosh; using std::atanh;
    using std::floor; using std::ceil;
    using std::abs; using std::max; using std::min;
    using cppode::exp; using cppode::log; using cppode::sqrt; using cppode::pow;
    using cppode::sin; using cppode::cos; using cppode::tan;
    using cppode::asin; using cppode::acos; using cppode::atan;
    using cppode::sinh; using cppode::cosh; using cppode::tanh;
    using cppode::asinh; using cppode::acosh; using cppode::atanh;
    using cppode::abs; using cppode::max; using cppode::min;
    (void)x_obs;

    y_local[0] = p[0];
    y_local[1] = p[1];
    y_local[2] = p[2];
}
} // anonymous namespace

extern "C" {

void expl_parfn_C1_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    double y_local[3];
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = nullptr;
        expl_parfn_C1_eval_one<double>(x_obs, p, y_local);
        for (int i = 0; i < n_out; ++i)
            y[obs + (size_t)n_obs * i] = y_local[i];
    }
}

void expl_parfn_C1_eval_ad(double* x, double* p, double* dX, double* dP,
                         double* y, double* dy,
                         int* n_obs_p, int* n_vars_p, int* n_params_p,
                         int* n_out_p, int* n_theta_p) {
    using AD = cppode::dual<double, 0>;
    const int n_obs    = *n_obs_p;
    const int n_vars   = *n_vars_p;
    const int n_params = *n_params_p;
    const int n_out    = *n_out_p;
    const int n_theta  = *n_theta_p;
    (void)n_vars; (void)n_params; (void)n_out;
    (void)dX; (void)dP;

    cppode::dual_arena::scope _eval_ad_scope;
    std::vector<AD> x_ad(0);
    std::vector<AD> p_ad(3);
    std::vector<AD> y_ad(3);

    // Seed parameters (time-invariant).
    for (int j = 0; j < n_params; ++j) {
        p_ad[j].x() = p[j];
        if (n_theta > 0) {
            p_ad[j].diff(0, n_theta);
            for (int k = 0; k < n_theta; ++k) {
                p_ad[j][k] = dP[j + n_params * k];
            }
        }
    }

    for (int obs = 0; obs < n_obs; ++obs) {
        expl_parfn_C1_eval_one<AD>(x_ad.data(), p_ad.data(), y_ad.data());
        for (int i = 0; i < n_out; ++i) {
            y[obs + (size_t)n_obs * i] = y_ad[i].val();
            for (int k = 0; k < n_theta; ++k) {
                dy[obs + (size_t)n_obs * (i + (size_t)n_out * k)] = y_ad[i].d(k);
            }
        }
    }
}

} // extern "C"
