/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

// Modelname: expl_parfn_steady
// Variables: none
// Parameters: Tca_canalicular, transport_Tca, export_Tca_baso, export_Tca_cana, import_Tca
// Outputs: Tca_buffer, Tca_cyto, Tca_canalicular, import_Tca, export_Tca_baso, transport_Tca, export_Tca_cana

namespace {
template <typename T>
inline void expl_parfn_steady_eval_one(const T* x_obs, const T* p, T* y_local) {
    using std::exp; using std::log; using std::sqrt; using std::pow;
    using std::sin; using std::cos; using std::tan;
    using std::asin; using std::acos; using std::atan; using std::atan2;
    using std::sinh; using std::cosh; using std::tanh;
    using std::asinh; using std::acosh; using std::atanh;
    using std::floor; using std::ceil;
    using std::abs; using std::max; using std::min;
    (void)x_obs;

    y_local[0] = p[0]*p[1]*(p[2] + p[3])/(p[3]*p[4]);
    y_local[1] = p[0]*p[1]/p[3];
    y_local[2] = p[0];
    y_local[3] = p[4];
    y_local[4] = p[2];
    y_local[5] = p[1];
    y_local[6] = p[3];
}
} // anonymous namespace

extern "C" {

void expl_parfn_steady_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    double y_local[7];
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = nullptr;
        expl_parfn_steady_eval_one<double>(x_obs, p, y_local);
        for (int i = 0; i < n_out; ++i)
            y[obs + (size_t)n_obs * i] = y_local[i];
    }
}

void expl_parfn_steady_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 7;
    const int n_symbols = 5;

    // Zero-initialize
    std::fill(jac, jac + (size_t)n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        jac[obs + (size_t)n_obs * (0 + n_out * 0)] = p[1]*(p[2] + p[3])/(p[3]*p[4]);
        jac[obs + (size_t)n_obs * (0 + n_out * 1)] = p[0]*(p[2] + p[3])/(p[3]*p[4]);
        jac[obs + (size_t)n_obs * (0 + n_out * 2)] = p[0]*p[1]/(p[3]*p[4]);
        jac[obs + (size_t)n_obs * (0 + n_out * 3)] = p[0]*p[1]/(p[3]*p[4]) - p[0]*p[1]*(p[2] + p[3])/(std::pow(p[3], 2.0)*p[4]);
        jac[obs + (size_t)n_obs * (0 + n_out * 4)] = -p[0]*p[1]*(p[2] + p[3])/(p[3]*std::pow(p[4], 2.0));

        jac[obs + (size_t)n_obs * (1 + n_out * 0)] = p[1]/p[3];
        jac[obs + (size_t)n_obs * (1 + n_out * 1)] = p[0]/p[3];
        jac[obs + (size_t)n_obs * (1 + n_out * 3)] = -p[0]*p[1]/std::pow(p[3], 2.0);

        jac[obs + (size_t)n_obs * (2 + n_out * 0)] = 1.0;

        jac[obs + (size_t)n_obs * (3 + n_out * 4)] = 1.0;

        jac[obs + (size_t)n_obs * (4 + n_out * 2)] = 1.0;

        jac[obs + (size_t)n_obs * (5 + n_out * 1)] = 1.0;

        jac[obs + (size_t)n_obs * (6 + n_out * 3)] = 1.0;
    }
}

} // extern "C"
