/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

// Modelname: obsfn
// Variables: none
// Parameters: s0
// Outputs: y

namespace {
template <typename T>
inline void obsfn_eval_one(const T* x_obs, const T* p, T* y_local) {
    using std::exp; using std::log; using std::sqrt; using std::pow;
    using std::sin; using std::cos; using std::tan;
    using std::asin; using std::acos; using std::atan; using std::atan2;
    using std::sinh; using std::cosh; using std::tanh;
    using std::asinh; using std::acosh; using std::atanh;
    using std::floor; using std::ceil;
    using std::abs; using std::max; using std::min;
    (void)x_obs;

    y_local[0] = p[0];
}
} // anonymous namespace

extern "C" {

void obsfn_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    double y_local[1];
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = nullptr;
        obsfn_eval_one<double>(x_obs, p, y_local);
        for (int i = 0; i < n_out; ++i)
            y[obs + (size_t)n_obs * i] = y_local[i];
    }
}

void obsfn_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 1;
    const int n_symbols = 1;

    // Zero-initialize
    std::fill(jac, jac + (size_t)n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        jac[obs + (size_t)n_obs * (0 + n_out * 0)] = 1.0;
    }
}

} // extern "C"
