/** Code auto-generated by cOde 1.1.2 **/
#include <R.h> 
 #include <math.h> 

static double parms[5];
static double forc[1];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 1 
#define precision 1e-05 

#define switch parms[0] 
 #define k parms[1] 
 #define y0_0 parms[2] 
 #define y1_0 parms[3] 
 #define y2_0 parms[4] 
 #define F forc[0] 
#define tmin range[0]
#define tmax range[1]


void odemodel_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=5;
	 odeparms(&N, parms);
}

void odemodel_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=1;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(switch*F)-1.0*(k*y[0]);
 	 ydot[1] = (-k)*(y[1]);
 	 ydot[2] = (-k)*(y[2])-y[0];

	 RPAR[0] = F;
}

