/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

extern "C" {

// Modelname: obsfn_bamodel
// Variables: TCA_buffer, TCA_cana, TCA_cell
// Parameters: s
// Outputs: buffer, cellular

void obsfn_bamodel_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = x + obs * n_vars;
        (void)x_obs;  // suppress unused warning

        y[obs * n_out + 0] = x_obs[0]*p[0];
        y[obs * n_out + 1] = p[0]*(x_obs[1] + x_obs[2]);
    }
}

void obsfn_bamodel_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 2;
    const int n_symbols = 4;

    // Zero-initialize
    std::fill(jac, jac + n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[output, symbol, obs] (R column-major)
    // Linear index: output + n_out * (symbol + n_symbols * obs)
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = x + obs * n_vars;
        (void)x_obs;  // suppress unused warning
        jac[0 + n_out * (0 + n_symbols * obs)] = p[0];        jac[0 + n_out * (3 + n_symbols * obs)] = x_obs[0];
        jac[1 + n_out * (1 + n_symbols * obs)] = p[0];        jac[1 + n_out * (2 + n_symbols * obs)] = p[0];        jac[1 + n_out * (3 + n_symbols * obs)] = x_obs[1] + x_obs[2];
    }
}

} // extern "C"
