/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>
#include <vector>
#include <fadbad++/fadiff.h>
#include <cppode/cppode_fadiff_extensions.hpp>

// Modelname: obsfn
// Variables: time
// Parameters: a, b
// Outputs: y

namespace {
template <typename T>
inline void obsfn_eval_one(const T* x_obs, const T* p, T* y_local) {
    using std::exp; using std::log; using std::sqrt; using std::pow;
    using std::sin; using std::cos; using std::tan;
    using std::asin; using std::acos; using std::atan; using std::atan2;
    using std::sinh; using std::cosh; using std::tanh;
    using std::asinh; using std::acosh; using std::atanh;
    using std::floor; using std::ceil;
    using std::abs; using std::max; using std::min;
    using fadbad::exp; using fadbad::log; using fadbad::sqrt; using fadbad::pow;
    using fadbad::sin; using fadbad::cos; using fadbad::tan;
    using fadbad::asin; using fadbad::acos; using fadbad::atan;
    using fadbad::sinh; using fadbad::cosh; using fadbad::tanh;
    using fadbad::asinh; using fadbad::acosh; using fadbad::atanh;
    using fadbad::abs; using fadbad::max; using fadbad::min;

    y_local[0] = p[0]*pow(x_obs[0], 2.0) + p[1];
}
} // anonymous namespace

extern "C" {

void obsfn_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    double y_local[1];
    for (int obs = 0; obs < n_obs; obs++) {
        const double* x_obs = x + obs * n_vars;
        obsfn_eval_one<double>(x_obs, p, y_local);
        for (int i = 0; i < n_out; ++i)
            y[obs + (size_t)n_obs * i] = y_local[i];
    }
}

void obsfn_eval_ad(double* x, double* p, double* dX, double* dP,
                         double* y, double* dy,
                         int* n_obs_p, int* n_vars_p, int* n_params_p,
                         int* n_out_p, int* n_theta_p) {
    using fadbad::F;
    const int n_obs    = *n_obs_p;
    const int n_vars   = *n_vars_p;
    const int n_params = *n_params_p;
    const int n_out    = *n_out_p;
    const int n_theta  = *n_theta_p;
    (void)n_vars; (void)n_params; (void)n_out;
    (void)dX; (void)dP;

    std::vector<F<double>> x_ad(1);
    std::vector<F<double>> p_ad(2);
    std::vector<F<double>> y_ad(1);

    // Seed parameters (time-invariant).
    for (int j = 0; j < n_params; ++j) {
        p_ad[j].x() = p[j];
        if (n_theta > 0) {
            p_ad[j].diff(0, n_theta);
            for (int k = 0; k < n_theta; ++k) {
                p_ad[j][k] = dP[j + n_params * k];
            }
        }
    }

    for (int obs = 0; obs < n_obs; ++obs) {
        for (int j = 0; j < n_vars; ++j) {
            x_ad[j].x() = x[j + n_vars * obs];
            if (n_theta > 0) {
                x_ad[j].diff(0, n_theta);
                for (int k = 0; k < n_theta; ++k) {
                    x_ad[j][k] = dX[obs + (size_t)n_obs * (j + (size_t)n_vars * k)];
                }
            }
        }
        obsfn_eval_one<F<double>>(x_ad.data(), p_ad.data(), y_ad.data());
        for (int i = 0; i < n_out; ++i) {
            y[obs + (size_t)n_obs * i] = y_ad[i].val();
            for (int k = 0; k < n_theta; ++k) {
                dy[obs + (size_t)n_obs * (i + (size_t)n_out * k)] = y_ad[i].deriv(k);
            }
        }
    }
}

} // extern "C"
