// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bmm_lb
NumericVector bmm_lb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_lb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_lb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_rb
NumericVector bmm_rb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_rb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_rb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_bb
NumericVector bmm_bb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_bb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_bb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dMod_bmm_lb", (DL_FUNC) &_dMod_bmm_lb, 6},
    {"_dMod_bmm_rb", (DL_FUNC) &_dMod_bmm_rb, 6},
    {"_dMod_bmm_bb", (DL_FUNC) &_dMod_bmm_bb, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dMod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
