// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bmm_lb
NumericVector bmm_lb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_lb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_lb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_rb
NumericVector bmm_rb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_rb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_rb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_bb
NumericVector bmm_bb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod_bmm_bb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_bb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// constraintL2_scalar_kernel
List constraintL2_scalar_kernel(NumericVector pars, Nullable<NumericMatrix> dP_opt, Nullable<NumericVector> dP2_opt, CharacterVector inner_par_names, Nullable<NumericVector> fixed_opt, CharacterVector mu_names, NumericVector mu, NumericVector sigma, CharacterVector sigma_pars, bool est, bool deriv);
RcppExport SEXP _dMod_constraintL2_scalar_kernel(SEXP parsSEXP, SEXP dP_optSEXP, SEXP dP2_optSEXP, SEXP inner_par_namesSEXP, SEXP fixed_optSEXP, SEXP mu_namesSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP sigma_parsSEXP, SEXP estSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dP_opt(dP_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dP2_opt(dP2_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type inner_par_names(inner_par_namesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type mu_names(mu_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sigma_pars(sigma_parsSEXP);
    Rcpp::traits::input_parameter< bool >::type est(estSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(constraintL2_scalar_kernel(pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv));
    return rcpp_result_gen;
END_RCPP
}
// datapointL2_kernel
List datapointL2_kernel(NumericVector pouter, Nullable<NumericVector> fixed_opt, NumericMatrix prdf, Nullable<NumericVector> dpred_attr_opt, Nullable<NumericVector> d2pred_attr_opt, std::string obs_name, double t, double sigma, std::string value_par, bool deriv);
RcppExport SEXP _dMod_datapointL2_kernel(SEXP pouterSEXP, SEXP fixed_optSEXP, SEXP prdfSEXP, SEXP dpred_attr_optSEXP, SEXP d2pred_attr_optSEXP, SEXP obs_nameSEXP, SEXP tSEXP, SEXP sigmaSEXP, SEXP value_parSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pouter(pouterSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prdf(prdfSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dpred_attr_opt(dpred_attr_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred_attr_opt(d2pred_attr_optSEXP);
    Rcpp::traits::input_parameter< std::string >::type obs_name(obs_nameSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< std::string >::type value_par(value_parSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(datapointL2_kernel(pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv));
    return rcpp_result_gen;
END_RCPP
}
// constraintL2_mvn_kernel
List constraintL2_mvn_kernel(NumericVector pars, Nullable<NumericVector> fixed_opt, Nullable<NumericMatrix> dP_opt, Nullable<NumericVector> dP2_opt, CharacterVector inner_par_names, int K, int N, CharacterVector all_eta_names, NumericVector mu, NumericMatrix L_lower, bool include_chol_block);
RcppExport SEXP _dMod_constraintL2_mvn_kernel(SEXP parsSEXP, SEXP fixed_optSEXP, SEXP dP_optSEXP, SEXP dP2_optSEXP, SEXP inner_par_namesSEXP, SEXP KSEXP, SEXP NSEXP, SEXP all_eta_namesSEXP, SEXP muSEXP, SEXP L_lowerSEXP, SEXP include_chol_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dP_opt(dP_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dP2_opt(dP2_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type inner_par_names(inner_par_namesSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type all_eta_names(all_eta_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L_lower(L_lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type include_chol_block(include_chol_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(constraintL2_mvn_kernel(pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block));
    return rcpp_result_gen;
END_RCPP
}
// focei_kernel_ping
List focei_kernel_ping(Function joint_cb, NumericVector pars, Nullable<NumericVector> fixed, CharacterVector conditions);
RcppExport SEXP _dMod_focei_kernel_ping(SEXP joint_cbSEXP, SEXP parsSEXP, SEXP fixedSEXP, SEXP conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type joint_cb(joint_cbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type conditions(conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(focei_kernel_ping(joint_cb, pars, fixed, conditions));
    return rcpp_result_gen;
END_RCPP
}
// focei_eval_one_subject
List focei_eval_one_subject(Function model_cb, Function err_cb, NumericVector pars_full, Nullable<NumericVector> fixed, List meta_i, NumericVector eta_block, NumericMatrix Omega_inv, double Omega_log_det);
RcppExport SEXP _dMod_focei_eval_one_subject(SEXP model_cbSEXP, SEXP err_cbSEXP, SEXP pars_fullSEXP, SEXP fixedSEXP, SEXP meta_iSEXP, SEXP eta_blockSEXP, SEXP Omega_invSEXP, SEXP Omega_log_detSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type model_cb(model_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type err_cb(err_cbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars_full(pars_fullSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< List >::type meta_i(meta_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta_block(eta_blockSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Omega_inv(Omega_invSEXP);
    Rcpp::traits::input_parameter< double >::type Omega_log_det(Omega_log_detSEXP);
    rcpp_result_gen = Rcpp::wrap(focei_eval_one_subject(model_cb, err_cb, pars_full, fixed, meta_i, eta_block, Omega_inv, Omega_log_det));
    return rcpp_result_gen;
END_RCPP
}
// focei_inner_trust
List focei_inner_trust(Function model_cb, Function err_cb, NumericVector pars_full, NumericMatrix eta_warmstart, List subject_meta, NumericMatrix Omega_inv_mat, double Omega_log_det, Nullable<NumericVector> fixed, List control);
RcppExport SEXP _dMod_focei_inner_trust(SEXP model_cbSEXP, SEXP err_cbSEXP, SEXP pars_fullSEXP, SEXP eta_warmstartSEXP, SEXP subject_metaSEXP, SEXP Omega_inv_matSEXP, SEXP Omega_log_detSEXP, SEXP fixedSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type model_cb(model_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type err_cb(err_cbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars_full(pars_fullSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta_warmstart(eta_warmstartSEXP);
    Rcpp::traits::input_parameter< List >::type subject_meta(subject_metaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Omega_inv_mat(Omega_inv_matSEXP);
    Rcpp::traits::input_parameter< double >::type Omega_log_det(Omega_log_detSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(focei_inner_trust(model_cb, err_cb, pars_full, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, control));
    return rcpp_result_gen;
END_RCPP
}
// focei_outer_objfn
List focei_outer_objfn(Function model_cb, Function err_cb, Function joint_cb, NumericVector outer_pars, NumericMatrix eta_warmstart, List subject_meta, NumericMatrix Omega_inv_mat, double Omega_log_det, Nullable<NumericVector> fixed, List inner_ctrl, std::string correction_mode, Nullable<Function> correction_cb_opt);
RcppExport SEXP _dMod_focei_outer_objfn(SEXP model_cbSEXP, SEXP err_cbSEXP, SEXP joint_cbSEXP, SEXP outer_parsSEXP, SEXP eta_warmstartSEXP, SEXP subject_metaSEXP, SEXP Omega_inv_matSEXP, SEXP Omega_log_detSEXP, SEXP fixedSEXP, SEXP inner_ctrlSEXP, SEXP correction_modeSEXP, SEXP correction_cb_optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type model_cb(model_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type err_cb(err_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type joint_cb(joint_cbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outer_pars(outer_parsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta_warmstart(eta_warmstartSEXP);
    Rcpp::traits::input_parameter< List >::type subject_meta(subject_metaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Omega_inv_mat(Omega_inv_matSEXP);
    Rcpp::traits::input_parameter< double >::type Omega_log_det(Omega_log_detSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< List >::type inner_ctrl(inner_ctrlSEXP);
    Rcpp::traits::input_parameter< std::string >::type correction_mode(correction_modeSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type correction_cb_opt(correction_cb_optSEXP);
    rcpp_result_gen = Rcpp::wrap(focei_outer_objfn(model_cb, err_cb, joint_cb, outer_pars, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, inner_ctrl, correction_mode, correction_cb_opt));
    return rcpp_result_gen;
END_RCPP
}
// focei_run
List focei_run(Function model_cb, Function err_cb, Function joint_cb, NumericVector init, List subject_meta, Nullable<NumericVector> fixed, List control, std::string correction_mode, Nullable<Function> correction_cb);
RcppExport SEXP _dMod_focei_run(SEXP model_cbSEXP, SEXP err_cbSEXP, SEXP joint_cbSEXP, SEXP initSEXP, SEXP subject_metaSEXP, SEXP fixedSEXP, SEXP controlSEXP, SEXP correction_modeSEXP, SEXP correction_cbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type model_cb(model_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type err_cb(err_cbSEXP);
    Rcpp::traits::input_parameter< Function >::type joint_cb(joint_cbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< List >::type subject_meta(subject_metaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type correction_mode(correction_modeSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type correction_cb(correction_cbSEXP);
    rcpp_result_gen = Rcpp::wrap(focei_run(model_cb, err_cb, joint_cb, init, subject_meta, fixed, control, correction_mode, correction_cb));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_chain_run
Rcpp::List mcmc_chain_run(Rcpp::Function objfun, Rcpp::NumericVector parinit, int n, int warmup, int moveType, Rcpp::List control, Rcpp::List bounds, Rcpp::NumericVector parscale_, Rcpp::Nullable<Rcpp::Function> dG_cb_opt);
RcppExport SEXP _dMod_mcmc_chain_run(SEXP objfunSEXP, SEXP parinitSEXP, SEXP nSEXP, SEXP warmupSEXP, SEXP moveTypeSEXP, SEXP controlSEXP, SEXP boundsSEXP, SEXP parscale_SEXP, SEXP dG_cb_optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type objfun(objfunSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< int >::type moveType(moveTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parscale_(parscale_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type dG_cb_opt(dG_cb_optSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_chain_run(objfun, parinit, n, warmup, moveType, control, bounds, parscale_, dG_cb_opt));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_smc_reweight
Rcpp::List mcmc_smc_reweight(const Rcpp::NumericVector& logL, const Rcpp::NumericVector& logwPrev, double betaOld, double betaNew);
RcppExport SEXP _dMod_mcmc_smc_reweight(SEXP logLSEXP, SEXP logwPrevSEXP, SEXP betaOldSEXP, SEXP betaNewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logL(logLSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logwPrev(logwPrevSEXP);
    Rcpp::traits::input_parameter< double >::type betaOld(betaOldSEXP);
    Rcpp::traits::input_parameter< double >::type betaNew(betaNewSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_smc_reweight(logL, logwPrev, betaOld, betaNew));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_stratified_resample
IntegerVector mcmc_stratified_resample(const NumericVector& weights);
RcppExport SEXP _dMod_mcmc_stratified_resample(SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_stratified_resample(weights));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_residual_resample
IntegerVector mcmc_residual_resample(const NumericVector& weights);
RcppExport SEXP _dMod_mcmc_residual_resample(SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_residual_resample(weights));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_multinomial_resample
IntegerVector mcmc_multinomial_resample(const NumericVector& weights);
RcppExport SEXP _dMod_mcmc_multinomial_resample(SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_multinomial_resample(weights));
    return rcpp_result_gen;
END_RCPP
}
// normL2_kernel
List normL2_kernel(List prediction, Nullable<List> err_list_opt, List meta_list, CharacterVector par_names_global, double bessel, bool deriv2_requested, int threads, std::string bloq_mode);
RcppExport SEXP _dMod_normL2_kernel(SEXP predictionSEXP, SEXP err_list_optSEXP, SEXP meta_listSEXP, SEXP par_names_globalSEXP, SEXP besselSEXP, SEXP deriv2_requestedSEXP, SEXP threadsSEXP, SEXP bloq_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type err_list_opt(err_list_optSEXP);
    Rcpp::traits::input_parameter< List >::type meta_list(meta_listSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type par_names_global(par_names_globalSEXP);
    Rcpp::traits::input_parameter< double >::type bessel(besselSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv2_requested(deriv2_requestedSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type bloq_mode(bloq_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(normL2_kernel(prediction, err_list_opt, meta_list, par_names_global, bessel, deriv2_requested, threads, bloq_mode));
    return rcpp_result_gen;
END_RCPP
}
// prior_omega_kernel
List prior_omega_kernel(NumericVector omegaVec, IntegerMatrix cholLoc, LogicalVector isDiag, int K, double lkjEta, double scaleSD, int kindFlag);
RcppExport SEXP _dMod_prior_omega_kernel(SEXP omegaVecSEXP, SEXP cholLocSEXP, SEXP isDiagSEXP, SEXP KSEXP, SEXP lkjEtaSEXP, SEXP scaleSDSEXP, SEXP kindFlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type omegaVec(omegaVecSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type cholLoc(cholLocSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type isDiag(isDiagSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type lkjEta(lkjEtaSEXP);
    Rcpp::traits::input_parameter< double >::type scaleSD(scaleSDSEXP);
    Rcpp::traits::input_parameter< int >::type kindFlag(kindFlagSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_omega_kernel(omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag));
    return rcpp_result_gen;
END_RCPP
}
// sparseGridGH
List sparseGridGH(int K, int level, int derivMode);
RcppExport SEXP _dMod_sparseGridGH(SEXP KSEXP, SEXP levelSEXP, SEXP derivModeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type derivMode(derivModeSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseGridGH(K, level, derivMode));
    return rcpp_result_gen;
END_RCPP
}
// residual_kernel_aloq
List residual_kernel_aloq(NumericVector pred, NumericMatrix dpred, Nullable<NumericVector> d2pred, NumericVector y_data, NumericVector sigma, Nullable<NumericMatrix> dsigma, Nullable<NumericVector> d2sigma, Nullable<NumericVector> lloq, List opts);
RcppExport SEXP _dMod_residual_kernel_aloq(SEXP predSEXP, SEXP dpredSEXP, SEXP d2predSEXP, SEXP y_dataSEXP, SEXP sigmaSEXP, SEXP dsigmaSEXP, SEXP d2sigmaSEXP, SEXP lloqSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred(d2predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_data(y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dsigma(dsigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2sigma(d2sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lloq(lloqSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(residual_kernel_aloq(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts));
    return rcpp_result_gen;
END_RCPP
}
// residual_kernel_bloq
List residual_kernel_bloq(NumericVector pred, NumericMatrix dpred, Nullable<NumericVector> d2pred, NumericVector y_data, NumericVector sigma, Nullable<NumericMatrix> dsigma, Nullable<NumericVector> d2sigma, Nullable<NumericVector> lloq, List opts);
RcppExport SEXP _dMod_residual_kernel_bloq(SEXP predSEXP, SEXP dpredSEXP, SEXP d2predSEXP, SEXP y_dataSEXP, SEXP sigmaSEXP, SEXP dsigmaSEXP, SEXP d2sigmaSEXP, SEXP lloqSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred(d2predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_data(y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dsigma(dsigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2sigma(d2sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lloq(lloqSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(residual_kernel_bloq(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts));
    return rcpp_result_gen;
END_RCPP
}
// smc_log_sum_exp
double smc_log_sum_exp(const NumericVector& x);
RcppExport SEXP _dMod_smc_log_sum_exp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_log_sum_exp(x));
    return rcpp_result_gen;
END_RCPP
}
// smc_ess
double smc_ess(const NumericVector& logw);
RcppExport SEXP _dMod_smc_ess(SEXP logwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type logw(logwSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_ess(logw));
    return rcpp_result_gen;
END_RCPP
}
// smc_systematic_resample
IntegerVector smc_systematic_resample(const NumericVector& weights, double u);
RcppExport SEXP _dMod_smc_systematic_resample(SEXP weightsSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_systematic_resample(weights, u));
    return rcpp_result_gen;
END_RCPP
}
// smc_beta_bisect
double smc_beta_bisect(const NumericVector& logL, const NumericVector& logwPrev, double betaOld, double targetESS, double tol, int maxIter);
RcppExport SEXP _dMod_smc_beta_bisect(SEXP logLSEXP, SEXP logwPrevSEXP, SEXP betaOldSEXP, SEXP targetESSSEXP, SEXP tolSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type logL(logLSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type logwPrev(logwPrevSEXP);
    Rcpp::traits::input_parameter< double >::type betaOld(betaOldSEXP);
    Rcpp::traits::input_parameter< double >::type targetESS(targetESSSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_beta_bisect(logL, logwPrev, betaOld, targetESS, tol, maxIter));
    return rcpp_result_gen;
END_RCPP
}
// trustL1_impl
List trustL1_impl(Function objfun, NumericVector parinit, NumericVector mu, NumericVector lambda, bool one_sided, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double fterm, double mterm, bool minimize, bool blather, Nullable<NumericVector> parupper, Nullable<NumericVector> parlower, bool printIter, Nullable<CharacterVector> traceFile);
RcppExport SEXP _dMod_trustL1_impl(SEXP objfunSEXP, SEXP parinitSEXP, SEXP muSEXP, SEXP lambdaSEXP, SEXP one_sidedSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftermSEXP, SEXP mtermSEXP, SEXP minimizeSEXP, SEXP blatherSEXP, SEXP parupperSEXP, SEXP parlowerSEXP, SEXP printIterSEXP, SEXP traceFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun(objfunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type one_sided(one_sidedSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type fterm(ftermSEXP);
    Rcpp::traits::input_parameter< double >::type mterm(mtermSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parupper(parupperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parlower(parlowerSEXP);
    Rcpp::traits::input_parameter< bool >::type printIter(printIterSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type traceFile(traceFileSEXP);
    rcpp_result_gen = Rcpp::wrap(trustL1_impl(objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather, parupper, parlower, printIter, traceFile));
    return rcpp_result_gen;
END_RCPP
}
// trust_impl
List trust_impl(Function objfun, NumericVector parinit, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double fterm, double mterm, bool minimize, bool blather, Nullable<NumericVector> parupper, Nullable<NumericVector> parlower, bool printIter, Nullable<CharacterVector> traceFile);
RcppExport SEXP _dMod_trust_impl(SEXP objfunSEXP, SEXP parinitSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftermSEXP, SEXP mtermSEXP, SEXP minimizeSEXP, SEXP blatherSEXP, SEXP parupperSEXP, SEXP parlowerSEXP, SEXP printIterSEXP, SEXP traceFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun(objfunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type fterm(ftermSEXP);
    Rcpp::traits::input_parameter< double >::type mterm(mtermSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parupper(parupperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parlower(parlowerSEXP);
    Rcpp::traits::input_parameter< bool >::type printIter(printIterSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type traceFile(traceFileSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_impl(objfun, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather, parupper, parlower, printIter, traceFile));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dMod_bmm_lb", (DL_FUNC) &_dMod_bmm_lb, 6},
    {"_dMod_bmm_rb", (DL_FUNC) &_dMod_bmm_rb, 6},
    {"_dMod_bmm_bb", (DL_FUNC) &_dMod_bmm_bb, 6},
    {"_dMod_constraintL2_scalar_kernel", (DL_FUNC) &_dMod_constraintL2_scalar_kernel, 11},
    {"_dMod_datapointL2_kernel", (DL_FUNC) &_dMod_datapointL2_kernel, 10},
    {"_dMod_constraintL2_mvn_kernel", (DL_FUNC) &_dMod_constraintL2_mvn_kernel, 11},
    {"_dMod_focei_kernel_ping", (DL_FUNC) &_dMod_focei_kernel_ping, 4},
    {"_dMod_focei_eval_one_subject", (DL_FUNC) &_dMod_focei_eval_one_subject, 8},
    {"_dMod_focei_inner_trust", (DL_FUNC) &_dMod_focei_inner_trust, 9},
    {"_dMod_focei_outer_objfn", (DL_FUNC) &_dMod_focei_outer_objfn, 12},
    {"_dMod_focei_run", (DL_FUNC) &_dMod_focei_run, 9},
    {"_dMod_mcmc_chain_run", (DL_FUNC) &_dMod_mcmc_chain_run, 9},
    {"_dMod_mcmc_smc_reweight", (DL_FUNC) &_dMod_mcmc_smc_reweight, 4},
    {"_dMod_mcmc_stratified_resample", (DL_FUNC) &_dMod_mcmc_stratified_resample, 1},
    {"_dMod_mcmc_residual_resample", (DL_FUNC) &_dMod_mcmc_residual_resample, 1},
    {"_dMod_mcmc_multinomial_resample", (DL_FUNC) &_dMod_mcmc_multinomial_resample, 1},
    {"_dMod_normL2_kernel", (DL_FUNC) &_dMod_normL2_kernel, 8},
    {"_dMod_prior_omega_kernel", (DL_FUNC) &_dMod_prior_omega_kernel, 7},
    {"_dMod_sparseGridGH", (DL_FUNC) &_dMod_sparseGridGH, 3},
    {"_dMod_residual_kernel_aloq", (DL_FUNC) &_dMod_residual_kernel_aloq, 9},
    {"_dMod_residual_kernel_bloq", (DL_FUNC) &_dMod_residual_kernel_bloq, 9},
    {"_dMod_smc_log_sum_exp", (DL_FUNC) &_dMod_smc_log_sum_exp, 1},
    {"_dMod_smc_ess", (DL_FUNC) &_dMod_smc_ess, 1},
    {"_dMod_smc_systematic_resample", (DL_FUNC) &_dMod_smc_systematic_resample, 2},
    {"_dMod_smc_beta_bisect", (DL_FUNC) &_dMod_smc_beta_bisect, 6},
    {"_dMod_trustL1_impl", (DL_FUNC) &_dMod_trustL1_impl, 17},
    {"_dMod_trust_impl", (DL_FUNC) &_dMod_trust_impl, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_dMod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
