# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bmm_lb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_lb`, A, B, Bn, M, K, N)
}

bmm_rb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_rb`, A, B, Bn, M, K, N)
}

bmm_bb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_bb`, A, B, Bn, M, K, N)
}

constraintL2_scalar_kernel <- function(pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv = TRUE) {
    .Call(`_dMod_constraintL2_scalar_kernel`, pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv)
}

datapointL2_kernel <- function(pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv = TRUE) {
    .Call(`_dMod_datapointL2_kernel`, pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv)
}

constraintL2_mvn_kernel <- function(pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block) {
    .Call(`_dMod_constraintL2_mvn_kernel`, pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block)
}

focei_kernel_ping <- function(joint_cb, pars, fixed, conditions) {
    .Call(`_dMod_focei_kernel_ping`, joint_cb, pars, fixed, conditions)
}

focei_eval_one_subject <- function(model_cb, err_cb, pars_full, fixed, meta_i, eta_block, Omega_inv, Omega_log_det) {
    .Call(`_dMod_focei_eval_one_subject`, model_cb, err_cb, pars_full, fixed, meta_i, eta_block, Omega_inv, Omega_log_det)
}

focei_inner_trust <- function(model_cb, err_cb, pars_full, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, control) {
    .Call(`_dMod_focei_inner_trust`, model_cb, err_cb, pars_full, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, control)
}

focei_outer_objfn <- function(model_cb, err_cb, joint_cb, outer_pars, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, inner_ctrl, correction_mode = "none", correction_cb_opt = NULL) {
    .Call(`_dMod_focei_outer_objfn`, model_cb, err_cb, joint_cb, outer_pars, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, inner_ctrl, correction_mode, correction_cb_opt)
}

focei_run <- function(model_cb, err_cb, joint_cb, init, subject_meta, fixed, control, correction_mode = "none", correction_cb = NULL) {
    .Call(`_dMod_focei_run`, model_cb, err_cb, joint_cb, init, subject_meta, fixed, control, correction_mode, correction_cb)
}

mcmcChainRun <- function(objfun, parinit, n, warmup, moveType, control, bounds, parscale_, dG_cb_opt) {
    .Call(`_dMod_mcmc_chain_run`, objfun, parinit, n, warmup, moveType, control, bounds, parscale_, dG_cb_opt)
}

mcmcSmcReweight <- function(logL, logwPrev, betaOld, betaNew) {
    .Call(`_dMod_mcmc_smc_reweight`, logL, logwPrev, betaOld, betaNew)
}

mcmcStratifiedResample <- function(weights) {
    .Call(`_dMod_mcmc_stratified_resample`, weights)
}

mcmcResidualResample <- function(weights) {
    .Call(`_dMod_mcmc_residual_resample`, weights)
}

mcmcMultinomialResample <- function(weights) {
    .Call(`_dMod_mcmc_multinomial_resample`, weights)
}

normL2_kernel <- function(prediction, err_list_opt, meta_list, par_names_global, bessel, deriv2_requested, threads, bloq_mode = "M3") {
    .Call(`_dMod_normL2_kernel`, prediction, err_list_opt, meta_list, par_names_global, bessel, deriv2_requested, threads, bloq_mode)
}

priorOmegaKernel <- function(omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag) {
    .Call(`_dMod_prior_omega_kernel`, omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag)
}

#' @name sparseGridGH
#' @title Sparse-grid Gauss-Hermite quadrature nodes (Smolyak rule)
#' @description Builds the K-dimensional Smolyak sparse grid for physicists'
#'   Gauss-Hermite at depth `level`. Returns nodes `[B, K]` in z-space and
#'   signed weights (length `B`).
#' @param K Integer >= 1, problem dimension.
#' @param level Integer >= K, Smolyak depth (K+1..K+3 is the useful range).
#' @param derivMode Reserved for future Genz-Keister / adaptive refinement;
#'   currently ignored.
#' @return A list with `nodes` (B x K, batch-first), `weights` (length B,
#'   signed), and `K`, `level`.
#' @export
sparseGridGH <- function(K, level, derivMode = 0L) {
    .Call(`_dMod_sparseGridGH`, K, level, derivMode)
}

residual_kernel_aloq <- function(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts) {
    .Call(`_dMod_residual_kernel_aloq`, pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts)
}

residual_kernel_bloq <- function(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts) {
    .Call(`_dMod_residual_kernel_bloq`, pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts)
}

smcLogSumExp <- function(x) {
    .Call(`_dMod_smc_log_sum_exp`, x)
}

smcESS <- function(logw) {
    .Call(`_dMod_smc_ess`, logw)
}

smcSystematicResample <- function(weights, u) {
    .Call(`_dMod_smc_systematic_resample`, weights, u)
}

smcBetaBisect <- function(logL, logwPrev, betaOld, targetESS, tol = 1e-6, maxIter = 80L) {
    .Call(`_dMod_smc_beta_bisect`, logL, logwPrev, betaOld, targetESS, tol, maxIter)
}

symObsNullMulti <- function(tapes, nLeaves, nStates, zSlots, point, pIn, Nt, cores = 1L) {
    .Call(`_dMod_symObsNullMulti`, tapes, nLeaves, nStates, zSlots, point, pIn, Nt, cores)
}

symObsNullBatch <- function(tapes, nLeaves, nStates, zSlots, points, primes, Nt, cores = 1L) {
    .Call(`_dMod_symObsNullBatch`, tapes, nLeaves, nStates, zSlots, points, primes, Nt, cores)
}

symObsNullChain <- function(chains, nLeaves, nStates, zSlots, point, pIn, Nt, Mtot, cores = 1L) {
    .Call(`_dMod_symObsNullChain`, chains, nLeaves, nStates, zSlots, point, pIn, Nt, Mtot, cores)
}

symObsNullChainSeedBatch <- function(chains, evalChain, seeds, primes, nLeaves, nStates, zSlots, Nt, Mtot, cores = 1L) {
    .Call(`_dMod_symObsNullChainSeedBatch`, chains, evalChain, seeds, primes, nLeaves, nStates, zSlots, Nt, Mtot, cores)
}

symSolveMod <- function(A, b, pIn) {
    .Call(`_dMod_symSolveMod`, A, b, pIn)
}

symRrefMod <- function(M, pIn) {
    .Call(`_dMod_symRrefMod`, M, pIn)
}

symFitRational <- function(sampleU, mons, rvals, pIn) {
    .Call(`_dMod_symFitRational`, sampleU, mons, rvals, pIn)
}

symRatRecon <- function(residues, primes) {
    .Call(`_dMod_symRatRecon`, residues, primes)
}

symSparsePoly <- function(seq, monoTab, monoRes, pIn) {
    .Call(`_dMod_symSparsePoly`, seq, monoTab, monoRes, pIn)
}

symMonoResidues <- function(expts, bases, pIn) {
    .Call(`_dMod_symMonoResidues`, expts, bases, pIn)
}

symBMorder <- function(seq, pIn) {
    .Call(`_dMod_symBMorder`, seq, pIn)
}

symCauchyEval <- function(tnodes, rvals, dN, dD, pIn) {
    .Call(`_dMod_symCauchyEval`, tnodes, rvals, dN, dD, pIn)
}

trustL1_impl <- function(objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale = NULL, iterlim = 100L, fterm = 1e-6, mterm = 1e-6, minimize = TRUE, blather = FALSE, parupper = NULL, parlower = NULL, printIter = FALSE, traceFile = NULL) {
    .Call(`_dMod_trustL1_impl`, objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather, parupper, parlower, printIter, traceFile)
}

trust_impl <- function(objfun, parinit, rinit, rmax, parscale = NULL, iterlim = 100L, fterm = 1e-6, mterm = 1e-6, minimize = TRUE, blather = FALSE, parupper = NULL, parlower = NULL, printIter = FALSE, traceFile = NULL) {
    .Call(`_dMod_trust_impl`, objfun, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather, parupper, parlower, printIter, traceFile)
}

