# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_batch_strided <- function() {
    .Call(`_dMod_has_batch_strided`)
}

bmm_lb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_lb`, A, B, Bn, M, K, N)
}

bmm_rb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_rb`, A, B, Bn, M, K, N)
}

bmm_bb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod_bmm_bb`, A, B, Bn, M, K, N)
}

